import {
  AnnotationNormalized,
  AnnotationPageNormalized,
  CanvasNormalized,
  CollectionNormalized,
  ManifestNormalized,
  RangeNormalized,
  ResourceProviderNormalized,
} from '@iiif/presentation-3-normalized';
import { _ServiceNormalized } from './serialize';
import { EMPTY } from './utilities';

export const emptyAnnotation: AnnotationNormalized = {
  id: 'https://iiif-parser/annotation',
  type: 'Annotation',
  behavior: EMPTY,
  label: null,
  thumbnail: EMPTY,
  summary: null,
  requiredStatement: null,
  metadata: EMPTY,
  seeAlso: EMPTY,
  homepage: EMPTY,
  rendering: EMPTY,
  service: EMPTY,
  accessibility: EMPTY,
  audience: EMPTY,
  body: EMPTY,
  bodyValue: null,
  canonical: null,
  created: null,
  creator: EMPTY,
  generated: null,
  generator: EMPTY,
  modified: null,
  motivation: EMPTY,
  rights: null as any, // @todo bug? should not be array of strings.
  stylesheet: null,
  target: EMPTY,
  timeMode: undefined, // @todo bug? should be null.
  via: EMPTY,
  partOf: EMPTY,
};

export const emptyAnnotationPage: AnnotationPageNormalized = {
  id: 'https://iiif-parser/annotation-page',
  type: 'AnnotationPage',
  behavior: EMPTY,
  label: null,
  thumbnail: EMPTY,
  summary: null,
  requiredStatement: null,
  metadata: EMPTY,
  rights: null,
  provider: EMPTY,
  items: EMPTY,
  seeAlso: EMPTY,
  homepage: EMPTY,
  rendering: EMPTY,
  service: EMPTY,
};

export const emptyCanvas: CanvasNormalized = {
  id: 'https://iiif-parser/empty-canvas',
  type: 'Canvas',
  label: null,
  behavior: EMPTY,
  thumbnail: EMPTY,
  accompanyingCanvas: null,
  placeholderCanvas: null,
  summary: null,
  requiredStatement: null,
  metadata: EMPTY,
  rights: null,
  navDate: null,
  provider: EMPTY,
  items: EMPTY,
  annotations: EMPTY,
  seeAlso: EMPTY,
  homepage: EMPTY,
  partOf: EMPTY,
  rendering: EMPTY,
  service: EMPTY,
  duration: 0,
  height: 0,
  width: 0,
};

export const emptyCollection: CollectionNormalized = {
  id: 'https://iiif-parser/empty-collection',
  type: 'Collection',
  label: null,
  viewingDirection: 'left-to-right',
  behavior: EMPTY,
  thumbnail: EMPTY,
  accompanyingCanvas: null,
  placeholderCanvas: null,
  summary: null,
  requiredStatement: null,
  metadata: EMPTY,
  rights: null,
  navDate: null,
  provider: EMPTY,
  items: EMPTY,
  annotations: EMPTY,
  seeAlso: EMPTY,
  homepage: EMPTY,
  partOf: EMPTY,
  rendering: EMPTY,
  service: EMPTY,
  services: EMPTY,
};

export const emptyManifest: ManifestNormalized = {
  id: 'https://iiif-parser/empty-manifest',
  type: 'Manifest',
  annotations: EMPTY,
  behavior: EMPTY,
  homepage: EMPTY,
  items: EMPTY,
  label: null,
  metadata: EMPTY,
  navDate: null,
  provider: EMPTY,
  partOf: EMPTY,
  accompanyingCanvas: null,
  placeholderCanvas: null,
  rendering: EMPTY,
  requiredStatement: null,
  rights: null,
  seeAlso: EMPTY,
  service: EMPTY,
  services: EMPTY,
  start: null,
  structures: EMPTY,
  summary: null,
  thumbnail: EMPTY,
  viewingDirection: 'left-to-right',
};

export const emptyRange: RangeNormalized = {
  id: 'https://iiif-parser/empty-canvas',
  type: 'Range',
  label: null,
  behavior: EMPTY,
  thumbnail: EMPTY,
  accompanyingCanvas: null,
  placeholderCanvas: null,
  summary: null,
  requiredStatement: null,
  metadata: EMPTY,
  rights: null,
  navDate: null,
  provider: EMPTY,
  items: EMPTY,
  annotations: EMPTY,
  seeAlso: EMPTY,
  homepage: EMPTY,
  partOf: EMPTY,
  rendering: EMPTY,
  service: EMPTY,
  start: null,
  supplementary: null,
  viewingDirection: 'left-to-right',
};

export const emptyAgent: ResourceProviderNormalized = {
  id: 'https://iiif-parser/empty-agent',
  type: 'Agent',
  label: {},
  logo: EMPTY,
  seeAlso: EMPTY,
  homepage: EMPTY,
};

export const emptyService: _ServiceNormalized = {
  id: 'https://iiif-parser/empty-service',
  type: 'UnknownService',
} as any;
