export const presentation4ClassRequirements = {
  spec: {
    name: "IIIF Presentation API 4.0 (preview) - Properties / Model",
    source: "https://preview.iiif.io/api/p4-composite/presentation/4.0/model/",
    generated: "2026-02-17",
  },
  classes: {
    Collection: {
      typeValue: "Collection",
      must: ["id", "type", "label"],
      should: ["metadata", "summary", "provider", "thumbnail", "items"],
      may: [
        "requiredStatement",
        "rights",
        "navDate",
        "navPlace",
        "placeholderContainer",
        "accompanyingContainer",
        "viewingDirection",
        "behavior",
        "seeAlso",
        "service",
        "services",
        "homepage",
        "rendering",
        "partOf",
        "start",
        "first",
        "last",
        "total",
        "canonical",
        "via",
        "annotations",
      ],
      mustNotNotes: [
        "If using Collection Pages (first/last), Collection must not use items; Collections with pages must have at least two pages.",
        "Collection Pages must not be embedded in Collections.",
        "Manifests must not be embedded within Collections (Collections may be embedded).",
      ],
    },

    CollectionPage: {
      typeValue: "CollectionPage",
      must: ["id", "type", "partOf", "items"],
      should: ["next", "prev"],
      may: [
        "startIndex",
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "behavior",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "canonical",
        "via",
        "annotations",
      ],
      mustNotNotes: ["Collection Pages must not be embedded within Collections."],
    },

    Manifest: {
      typeValue: "Manifest",
      must: ["id", "type", "label", "items"],
      should: ["metadata", "summary", "provider", "thumbnail"],
      may: [
        "requiredStatement",
        "rights",
        "navDate",
        "navPlace",
        "placeholderContainer",
        "accompanyingContainer",
        "viewingDirection",
        "behavior",
        "seeAlso",
        "service",
        "services",
        "homepage",
        "rendering",
        "partOf",
        "start",
        "canonical",
        "via",
        "structures",
        "annotations",
      ],
      mustNotNotes: [
        "Manifest items must be Containers and must be embedded within the Manifest.",
        "Manifest annotations (about the Manifest) must not have motivation=painting.",
      ],
    },

    Range: {
      typeValue: "Range",
      must: ["id", "type"],
      should: ["label", "items"],
      may: [
        "start",
        "supplementary",
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "navDate",
        "navPlace",
        "placeholderContainer",
        "accompanyingContainer",
        "viewingDirection",
        "behavior",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "partOf",
        "canonical",
        "via",
        "annotations",
      ],
    },

    Timeline: {
      typeValue: "Timeline",
      must: ["id", "type", "duration"],
      should: ["label", "items"],
      may: [
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "navDate",
        "navPlace",
        "placeholderContainer",
        "accompanyingContainer",
        "behavior",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "partOf",
        "canonical",
        "via",
        "annotations",
      ],
    },

    Canvas: {
      typeValue: "Canvas",
      must: ["id", "type", "height", "width"],
      should: ["label", "items"],
      may: [
        "duration",
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "navDate",
        "navPlace",
        "placeholderContainer",
        "accompanyingContainer",
        "behavior",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "partOf",
        "canonical",
        "via",
        "annotations",
      ],
      mustNotNotes: ["Container ids must not include URI fragments (#...) (applies to all Containers)."],
    },

    Scene: {
      typeValue: "Scene",
      must: ["id", "type"],
      should: ["label", "items"],
      may: [
        "duration",
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "navDate",
        "navPlace",
        "placeholderContainer",
        "accompanyingContainer",
        "behavior",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "partOf",
        "canonical",
        "via",
        "annotations",
      ],
      mustNotNotes: [
        "Non-3D content resources must not be painted directly into a Scene; paint onto a Canvas then paint that Canvas into the Scene (audio via AudioEmitter).",
      ],
    },

    AnnotationCollection: {
      typeValue: "AnnotationCollection",
      must: ["id", "type", "label", "first", "last"],
      should: ["metadata", "summary", "provider", "thumbnail"],
      may: [
        "requiredStatement",
        "rights",
        "navDate",
        "navPlace",
        "placeholderContainer",
        "accompanyingContainer",
        "viewingDirection",
        "behavior",
        "seeAlso",
        "service",
        "services",
        "homepage",
        "rendering",
        "partOf",
        "start",
        "total",
        "canonical",
        "via",
        "annotations",
      ],
    },

    AnnotationPage: {
      typeValue: "AnnotationPage",
      must: ["id", "type", "items"],
      should: ["next", "prev", "partOf"],
      may: [
        "label",
        "startIndex",
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "behavior",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "canonical",
        "via",
        "annotations",
      ],
    },

    Annotation: {
      typeValue: "Annotation",
      must: ["id", "type", "target", "motivation"],
      should: ["body"],
      may: [
        "label",
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "navDate",
        "navPlace",
        "provides",
        "behavior",
        "timeMode",
        "stylesheet",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "partOf",
        "canonical",
        "via",
      ],
      mustNotNotes: ["IIIF prohibits Web Annotation bodyValue; use TextualBody instead."],
    },

    SpecificResource: {
      typeValue: "SpecificResource",
      must: ["id", "type", "source"],
      should: ["selector"],
      may: [
        "position",
        "transform",
        "scope",
        "styleClass",
        "height",
        "width",
        "duration",
        "language",
        "label",
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "behavior",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "canonical",
        "via",
        "annotations",
      ],
    },

    TextualBody: {
      typeValue: "TextualBody",
      must: ["type", "value"],
      should: [],
      may: [
        "id",
        "position",
        "transform",
        "scope",
        "styleClass",
        "height",
        "width",
        "duration",
        "language",
        "format",
        "label",
        "metadata",
        "summary",
        "provider",
        "thumbnail",
        "requiredStatement",
        "rights",
        "behavior",
        "seeAlso",
        "service",
        "homepage",
        "rendering",
        "canonical",
        "via",
        "annotations",
      ],
    },

    Choice: {
      typeValue: "Choice",
      must: ["type", "items"],
      should: ["label"],
      may: ["id", "metadata", "summary", "provider", "thumbnail", "requiredStatement", "behavior", "seeAlso"],
    },

    Composite: {
      typeValue: "Composite",
      must: ["type", "items"],
      should: ["label"],
      may: ["id", "metadata", "summary", "provider", "thumbnail", "requiredStatement", "behavior", "seeAlso"],
    },

    List: {
      typeValue: "List",
      must: ["type", "items"],
      should: ["label"],
      may: ["id", "metadata", "summary", "provider", "thumbnail", "requiredStatement", "behavior", "seeAlso"],
    },

    Independents: {
      typeValue: "Independents",
      must: ["type", "items"],
      should: ["label"],
      may: ["id", "metadata", "summary", "provider", "thumbnail", "requiredStatement", "behavior", "seeAlso"],
    },

    Service: {
      typeValue: "Service",
      must: ["id", "type"],
      should: ["label", "profile"],
      may: ["service", "@id", "@type"],
    },

    Agent: {
      typeValue: "Agent",
      must: ["type", "label"],
      should: ["homepage", "logo"],
      may: ["id", "seeAlso", "summary"],
    },

    PointSelector: {
      typeValue: "PointSelector",
      must: ["type"],
      should: [],
      may: ["id", "x", "y", "z", "instant"],
    },

    WktSelector: {
      typeValue: "WktSelector",
      must: ["type", "value"],
      should: [],
      may: ["id"],
    },
  },
};

// Backward-compatible alias while callsites migrate.
export const presentation3ClassRequirements = presentation4ClassRequirements;
