/**
 * Presentation 4 property inventory grouped for documentation and type work.
 */

const all = [
  "accompanyingContainer",
  "action",
  "angle",
  "annotations",
  "backgroundColor",
  "behavior",
  "body",
  "canonical",
  "color",
  "duration",
  "exclude",
  "far",
  "fieldOfView",
  "fileSize",
  "first",
  "format",
  "height",
  "homepage",
  "id",
  "instant",
  "intensity",
  "interactionMode",
  "items",
  "label",
  "language",
  "last",
  "logo",
  "lookAt",
  "metadata",
  "motivation",
  "navDate",
  "navPlace",
  "near",
  "next",
  "partOf",
  "placeholderContainer",
  "position",
  "prev",
  "profile",
  "provider",
  "provides",
  "quality",
  "quantityValue",
  "refinedBy",
  "region",
  "rendering",
  "requiredStatement",
  "rights",
  "rotation",
  "seeAlso",
  "selector",
  "service",
  "services",
  "size",
  "source",
  "spatialScale",
  "start",
  "startIndex",
  "structures",
  "styleClass",
  "stylesheet",
  "summary",
  "supplementary",
  "target",
  "temporalScale",
  "thumbnail",
  "timeMode",
  "total",
  "transform",
  "type",
  "unit",
  "value",
  "version",
  "via",
  "viewingDirection",
  "volume",
  "width",
  "x",
  "y",
  "z"
] as const;

export type Presentation4PropertyName = (typeof all)[number];

export const properties = {
  all,
  categories: {
  "technical": [
    "behavior",
    "duration",
    "fileSize",
    "format",
    "height",
    "id",
    "language",
    "profile",
    "timeMode",
    "type",
    "version",
    "viewingDirection",
    "width"
  ],
  "descriptive": [
    "label",
    "metadata",
    "navDate",
    "provider",
    "requiredStatement",
    "rights",
    "summary",
    "thumbnail"
  ],
  "linking": [
    "canonical",
    "homepage",
    "logo",
    "partOf",
    "rendering",
    "seeAlso",
    "service",
    "services",
    "start",
    "supplementary",
    "via"
  ],
  "structural": [
    "annotations",
    "body",
    "first",
    "items",
    "last",
    "next",
    "prev",
    "selector",
    "source",
    "startIndex",
    "structures",
    "target",
    "total"
  ],
  "spatialTemporal": [
    "angle",
    "backgroundColor",
    "color",
    "far",
    "fieldOfView",
    "instant",
    "intensity",
    "lookAt",
    "near",
    "position",
    "quality",
    "quantityValue",
    "region",
    "rotation",
    "size",
    "spatialScale",
    "temporalScale",
    "unit",
    "value",
    "volume",
    "x",
    "y",
    "z"
  ],
  "interaction": [
    "accompanyingContainer",
    "action",
    "exclude",
    "interactionMode",
    "motivation",
    "navPlace",
    "placeholderContainer",
    "provides",
    "styleClass",
    "stylesheet",
    "transform"
  ],
  "other": [
    "refinedBy"
  ]
} as const,
} as const;
