name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20']

    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run lint
      - run: pnpm run typecheck
      - run: node pkg-tests/node-load.cjs
      - run: node pkg-tests/node-load.mjs
